---
apiVersion: v1
kind: Pod
metadata:
  name: k8s-arbitrage
spec:
  containers:
    - name: arbitrage
      image: k8s-arbitrage:0.3
      volumeMounts:
        - mountPath: "/data"
          name: data-pv
  volumes:
    - name: data-pv
      persistentVolumeClaim:
        claimName: data-pv
